In [14]:
import numpy as np


In [6]:
arr=numpy.array([1,2,3,4,5])
print(arr)
print(numpy.__version__)
print(type(arr))

[1 2 3 4 5]
1.20.1
<class 'numpy.ndarray'>


In [7]:
arr=np.array([[[[[1,2,3]]]]])
print(arr.ndim)

5


In [37]:
arr=np.array([1,2,3],ndmin=5)
print(arr)
print("no.of dime: ",arr.ndim)

[[[[[1 2 3]]]]]
no.of dime:  5


In [27]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1,2])   #---> 1 is postition of array  2 is position of element
print(a[0:3,1])
print(a[-1])
print(a[-1,0:2])
print(a[:,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[2 5 8]
[7 8 9]
[7 8]
[[2 3]
 [5 6]
 [8 9]]


In [34]:
arr=np.array([1,0,3],dtype=bool)
# bo=arr.astyle(bool)
print(arr)
print(arr.dtype)

[ True False  True]
bool


In [35]:
arr=np.array([1,2,3])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3]


In [36]:
## shape
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [42]:
arr=np.array([1,2,3,6],ndmin=5)
print(arr)
print('shape:',arr.shape)

[[[[[1 2 3 6]]]]]
shape: (1, 1, 1, 1, 4)


In [47]:
# Reshape
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
r1=arr.reshape(4,3)
r2=arr.reshape(2,3,2)
print(r1)
print(r2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [19]:
a=np.arange(12).reshape(3,4)
print(a)

for row in a:
    print(row)
    
for x in np.nditer(a,order='c'):
    print(x,end=" ")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 

In [18]:
for x in np.nditer(a,order='F'):
    print(x,end=" ")

0 4 8 1 5 9 2 6 10 3 7 11 

In [65]:
b=np.arange(3,15,4).reshape(3,1)
print(b)

[[ 3]
 [ 7]
 [11]]


In [70]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [82]:
a=np.arange(30).reshape(2,15)
print(a)

print('**************************')
print(np.hsplit(a,3))
print('**************************')
print(np.vsplit(a,2))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
**************************
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
**************************
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [74]:
# BOOL

a=np.arange(12).reshape(3,4)
print(a)
b=a>4
print(b)
print(a[b])
a[b]=-1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [98]:
from numpy import random
x=random.randint(101,112)
print(x)

107


In [3]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[82 58 53 99 44]
 [35 77  4 64 19]
 [76 28 56 49 71]]


In [86]:
y=random.rand(3)
x=random.rand(3,5)
print(x)
print(y)

[[0.42181344 0.28525937 0.14177415 0.62681662 0.83697484]
 [0.53221779 0.0659976  0.45541747 0.55019299 0.83269108]
 [0.89594921 0.74914292 0.22379868 0.41945479 0.13807477]]
[0.72446768 0.4463322  0.07113145]


In [7]:
import numpy
c=random.choice([3,5,4,6])
print(c)

4


In [12]:
print(random.rand())
print(random.randint(5))

0.4612684413376461
1
